language: c
sudo: required
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libmcrypt-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libt1-dev
      - cpanminus
compiler:
  - gcc
cache:
  - apt
env:
  - PHP_SRC_VERSION=7.0.26
    NGINX_SRC_VERSION=1.10.3
  - PHP_SRC_VERSION=7.1.12
    NGINX_SRC_VERSION=1.10.3
  - PHP_SRC_VERSION=7.2.0
    NGINX_SRC_VERSION=1.10.3
install:
  - sudo cpanm -n Test::Nginx
before_script:
  - ./.travis/compiler.sh
script:
  - ./.travis/test.sh
