language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libmcrypt-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libt1-dev
      - cpanminus
      - openssl
      - libssl-dev
      - libbz2-dev
      - libzip-dev
      - systemtap-sdt-dev
      - libonig-dev
compiler:
  - gcc
  - clang
cache:
  apt: true
  directories:
  - data-cache
env:
  - PHP_SRC_VERSION=7.0.33
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.1.33
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.2.24
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.3.11
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.4.0RC1
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.4.0RC2
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.4.0RC3
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.4.0RC4
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.2.24
    NGINX_SRC_VERSION=1.12.2
    NGINX_MODULE=DYNAMIC
services:
  - memcache
  - mysql
install:
  - sudo cpanm -n Test::Nginx
before_script:
  - mysql -uroot -e 'create database ngx_php; grant all on ngx_php.* to "ngx_php"@"%" identified by "ngx_php"; flush privileges;'
  - if [ ! -d data-cache ]; then mkdir data-cache; fi
  - if [ ! -f data-cache/world.sql.gz ]; then wget -O data-cache/world.sql.gz http://downloads.mysql.com/docs/world.sql.gz; fi
  - zcat data-cache/world.sql.gz | mysql -uroot
  - mysql -uroot -e 'grant all on world.* to "ngx_php"@"%"; flush privileges;'
  - ./.travis/compiler.sh
script:
  - ./.travis/test.sh
