language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libmcrypt-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libt1-dev
      - cpanminus
      - openssl
      - libssl-dev
      - libbz2-dev
      - libzip-dev
compiler:
  - gcc
  - clang
cache:
  - apt
env:
  - PHP_SRC_VERSION=7.0.32
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.1.24
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.2.12
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.3.0
    NGINX_SRC_VERSION=1.12.2
  - PHP_SRC_VERSION=7.1.24
    NGINX_SRC_VERSION=1.12.2
    NGINX_MODULE=DYNAMIC
install:
  - sudo cpanm -n Test::Nginx
before_script:
  - ./.travis/compiler.sh
script:
  - ./.travis/test.sh
