name: Build

on:
  push:
    paths:
      - "src/**"
      - "t/**"
      - "third_party/**"
      - ".github/**"
  pull_request:
    paths:
      - "src/**"
      - "t/**"
      - "third_party/**"
      - ".github/**"

# later try to pass it, and not repeat it in workflows 
env:
  DB_DATABASE: ngx_php
  DB_USER: ngx_php
  DB_PASSWORD: ngx_php

jobs:
  build_php_22-04:
    name: Compile PHP Ubuntu 22.04
    if: ${{ contains(github.event.head_commit.message, '#compile') }}
    uses: ./.github/workflows/build_22.04_compile_php.yml

  build_20-04:
    name: Ubuntu 20.04
    if: ${{ !contains(github.event.head_commit.message, '#20') }}
    uses: ./.github/workflows/build_20.04.yml
    
  build_dynamic_20-04:
    name: Ubuntu 20.04 dynamic
    if: ${{ !contains(github.event.head_commit.message, '#20') }}
    uses: ./.github/workflows/build_20.04_dynamic.yml

  build_dynamic_22-04:
    name: Ubuntu 22.04 dynamic
    if: ${{ !contains(github.event.head_commit.message, '#22') }}
    uses: ./.github/workflows/build_22.04_dynamic.yml

